# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    # 下载代码
    - uses: actions/checkout@v2
    # 安装Nodejs
    # - name: Setup Node.js 13.2.0
    #   uses: actions/setup-node@v1
    #   with:
    #     node-version: 13.2.0
    # # 安装依赖和编译
    # - name: Npm install and build
    #   # 运行的命令或者 action
    #   run: |
    #     npm install
    #     npm run build
    # 部署到阿里云
    - name: Deploy to Aliyun
      uses: easingthemes/ssh-deploy@v2.1.1
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        ARGS: "-avzr --delete"
        SOURCE: "./doc/xmind"
        REMOTE_HOST: "47.98.252.43"
        REMOTE_USER: "root"
        TARGET: "/root/vuepress"